plugin:
    name: 'octommerce.octommerce::lang.plugin.name'
    description: 'octommerce.octommerce::lang.plugin.description'
    author: 'Octommerce'
    icon: icon-shopping-cart
    homepage: 'http://octommerce.com'
navigation:
    products:
        label: Products
        url: octommerce/octommerce/products
        icon: icon-tags
        permissions:
            - octommerce.octommerce.access_products
        order: '300'
        sideMenu:
            products:
                label: 'All Products'
                url: octommerce/octommerce/products
                icon: icon-barcode
            attributes:
                label: Attributes
                url: octommerce/octommerce/productattributes
                icon: icon-flag
            categories:
                label: Categories
                url: octommerce/octommerce/categories
                icon: icon-table
            brands:
                label: Brands
                url: octommerce/octommerce/brands
                icon: icon-eye
            lists:
                label: Lists
                url: octommerce/octommerce/productlists
                icon: icon-reorder
            reviews:
                label: Reviews
                url: octommerce/octommerce/reviews
                icon: icon-comments
            wishlists:
                label: Wishlist
                url: octommerce/octommerce/wishlists
                icon: icon-heart
    commerce:
        label: Commerce
        url: octommerce/octommerce/orders
        icon: icon-shopping-cart
        order: '310'
        sideMenu:
            orders:
                label: Orders
                url: octommerce/octommerce/orders
                icon: icon-shopping-cart
                permissions:
                    - octommerce.octommerce.access_orders
            orderstatuses:
                label: 'Order Statuses'
                url: octommerce/octommerce/orderstatuses
                icon: icon-tasks
                permissions:
                    - octommerce.octommerce.manage_order_statuses
permissions:
    octommerce.octommerce.access_products:
        tab: Products
        label: 'Access Products'
    octommerce.octommerce.access_orders:
        tab: Commerce
        label: 'Access Orders'
    octommerce.octommerce.manage_order_statuses:
        tab: Commerce
        label: 'Manage Order Statuses'
