# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Variation

# Model Form Field configuration
form: $/octommerce/octommerce/models/variation/fields.yaml

# Model Class name
modelClass: Octommerce\Octommerce\Models\Variation

# Default redirect location
defaultRedirect: octommerce/octommerce/variations

# Create page
create:
    title: Create Variation
    redirect: octommerce/octommerce/variations/update/:id
    redirectClose: octommerce/octommerce/variations

# Update page
update:
    title: Edit Variation
    redirect: octommerce/octommerce/variations
    redirectClose: octommerce/octommerce/variations

# Preview page
preview:
    title: Preview Variation
